### ISSUE TITLE
Elemzés futtatása parancssorból

### ISSUE THREAD

**Issue by kocsrobert** [ELTE-DH/emtsv-wiki#1]
Kedves Fejlesztők!

Köszönöm a leírást, az elemzés sikeresen lefutott. Segítséget szeretnék kérni a parancssorból való elemzés futtatásához.

Köszönöm

**Comment by levaid** [comment]
Windowson sajnos kicsit fájdalmas, de meg lehet oldani a parancssorból való futtatást. UTF-8-as bementi fájlt feltételez az alábbi leírásom.

Ehhez is Powershellt kell nyitni, odanavigálni a fájlhoz, majd be kell állítani a karakterkódolást: (ez az öt sor + ENTER)

```powershell
$InputEncoding = [System.Text.UTF8Encoding]::new()
$OutputEncoding = [System.Text.UTF8Encoding]::new()
[console]::InputEncoding = [System.Text.UTF8Encoding]::new()
[console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
```

Majd a kimenetet elmentjük egy változóba: 

```powershell
$MyRawString = cat -Encoding utf8 .\intext_utf8.txt.txt | docker run -i mtaril/emtsv tok,morph,pos
```

Majd kiírjuk fájlba (az első sor azért kell, mert a második sor függvénye rosszul kezeli az elérési utat):
```powershell
[System.Environment]::CurrentDirectory = (Get-Location).Path
[System.IO.File]::WriteAllLines('test_utf8_out.tsv', $MyRawString, $Utf8NoBomEncoding)
```

A bemeneti és kimeneti fájlokat értelemszerűen meg kell adni (ez a példámban `intext_utf8.txt.txt` és `test_utf8_out.tsv`).

Összességében a script:

```powershell
$InputEncoding = [System.Text.UTF8Encoding]::new()
$OutputEncoding = [System.Text.UTF8Encoding]::new()
[console]::InputEncoding = [System.Text.UTF8Encoding]::new()
[console]::OutputEncoding = [System.Text.UTF8Encoding]::new()
$Utf8NoBomEncoding = New-Object System.Text.UTF8Encoding $False
$MyRawString = cat -Encoding utf8 .\intext_utf8.txt.txt | docker run -i mtaril/emtsv tok,morph,pos
[System.Environment]::CurrentDirectory = (Get-Location).Path
[System.IO.File]::WriteAllLines('test_utf8_out.tsv', $MyRawString, $Utf8NoBomEncoding)
```

Futtasd le és írj ide, hogy működött-e.

**Comment by aknap** [comment]
Kedves Mindenki,
Kipróbáltam, nekem működik a fenti megoldás (Windows 10 PowerShell-ben).
Köszönjük a leírást.

**Comment by kocsrobert** [comment]
Igen, nekem is működik :-) Köszönöm.
Most épp linuxon próbálom életre kelteni a rendszert :-)
